# Generated by Django 5.2.1 on 2025-05-20 19:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SimulationModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("total_iterations", models.IntegerField()),
                ("initial_price", models.FloatField()),
                ("initial_stock", models.IntegerField()),
                ("final_price", models.FloatField(default=0.0)),
                ("price_history", models.JSONField(default=list)),
                ("random_agents", models.IntegerField()),
                ("trend_agents", models.IntegerField()),
                ("antitrend_agents", models.IntegerField()),
                ("smart_agents", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="EventModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("agent_id", models.IntegerField()),
                ("event_type", models.CharField(max_length=50)),
                ("payload", models.JSONField()),
                ("iteration", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "simulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="market_simulation.simulationmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentBalanceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agent_id", models.IntegerField()),
                ("agent_type", models.CharField(max_length=50)),
                ("balance", models.FloatField()),
                ("inventory", models.IntegerField()),
                (
                    "simulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_balances",
                        to="market_simulation.simulationmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("agent_id", models.IntegerField()),
                (
                    "action",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=4
                    ),
                ),
                ("price", models.FloatField()),
                ("iteration", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "simulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="market_simulation.simulationmodel",
                    ),
                ),
            ],
        ),
    ]
