# Generated by Django 5.2.1 on 2025-05-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_simulation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulationmodel",
            name="final_stock",
            field=models.IntegerField(default=0),
        ),
    ]
